name: Extract application configuration
on:
  push:
    branches:
      - 'feature/*'
jobs:
  config:
    name: Prepare configuration
    runs-on: ubuntu-latest
    outputs:
      config: ${{ steps.extract-config.outputs.config }}
      java-version: ${{ fromJson(steps.extract-config.outputs.config).java.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract project configuration
        id: extract-config
        run: |
          echo "config=$(jq -c '.' '.github/app-config.json')" >> "$GITHUB_OUTPUT"

  evaluate:
    name: Evaluate configuration
    runs-on: ubuntu-latest
    needs: config
    steps:
      - name: Print configuration
        run: |
          echo ${{ needs.config.outputs.java-version }}

#   config-attribute-not-provided:
#     name: Prepare configuration
#     runs-on: ubuntu-latest
#     outputs:
#       java-version: ${{ fromJson(steps.extract-config.outputs.cfg).java.version }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Extract project configuration
#         id: extract-config
#         run: |
#           echo "cfg=$(jq -c '.' '.github/appcfg-empty.json')" >> "$GITHUB_OUTPUT"
#     config-file-not-provided:
#         name: Prepare configuration
#         runs-on: ubuntu-latest
#         outputs:
#             java-version: ${{ fromJson(steps.extract-config.outputs.cfg).java.version }}
#         steps:
#             - name: Checkout
#             uses: actions/checkout@v3
#             - name: Extract project configuration
#             id: extract-config
#             run: |
#                 echo "cfg=$(jq -c '.' '.github/appcfg-empty.json')" >> "$GITHUB_OUTPUT"        