name: Extract configuration
on:
  push:
    branches:
      - 'feature/*'
jobs:
  config:
    name: Prepare configuration
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ fromJson(steps.extract-config.outputs.cfg).java.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract project configuration
        id: extract-config
        run: |
          echo "cfg=$(jq -c '.' '.github/appcfg-empty.json')" >> "$GITHUB_OUTPUT"