name: Environment Variables
on:
  push:
    branches:
      - 'feature/*'
jobs:
  generate-env-variables:
    name: Generate Environment Variables
    runs-on: ubuntu-latest
    env:
      NUMBER: 42      
    steps:
      - name: Print number
        run: |
          echo "Number=$NUMBER"  
      - name: Set and Retrieve Github ENV variables
        shell: bash
        run: |

          # define variables      
          tests=16
          failures=2

          # set them as GitHub ENV variables
          echo "TESTS=$tests" >> $GITHUB_ENV
          echo "FAILURES=$failures" >> $GITHUB_ENV

          # retrieve these GitHub ENV variables
          echo "${{ env.FAILURES }} out of ${{ env.TESTS }} tests failed on CI"  
      - name: Print all Environment Variables
        run: |
          env    
      - name: Display Environment Variables
        run: |
          echo "Tests=$TESTS"
          echo "Failures=$FAILURES"  
          

          

            
