name: Environment Variables
on:
  push:
    branches:
      - 'feature/*'
jobs:
  generate-env-variables:
    name: Generate Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Set and Retrieve Github ENV variables
        shell: bash
        run: |

          # define variables      
          tests=16
          failures=2

          # set them as GitHub ENV variables
          echo "Tests=$tests" >> $GITHUB_ENV
          echo "Failures=$failures" >> $GITHUB_ENV

          # retrieve these GitHub ENV variables
          echo "${{ env.Failures }} out of ${{ env.Tests }} tests failed on CI"  
      - name: Display Environment Variables
        run: |
          echo "Tests=$TESTS"
          echo "Failures=$FAILURES"  
          

          

            
