name: JSON Object as a Job Output
on:
  workflow_dispatch:  
  push:
    branches:
      - 'feature/*'  
jobs:
  jsob-expression-in-github:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Populate JSON object
        shell: bash
        env:
          JSON: '{"name": "John", "age": 30, "city": "New York"}'
        run: |
          echo "JSON=$JSON" >> $GITHUB_ENV
          echo "JSON=$JSON"
          echo "string value=${{ env.JSON }}"
          echo "json object (toJson(str)) =${{ toJson(env.JSON) }}"
          echo "name=${{ fromJson(env.JSON).name }}"
          echo "age=${{ fromJson(env.JSON).age }}"
          echo "city=${{ fromJson(env.JSON).city }}"
          echo "json object (fromJSON(str))=${{ fromJson(env.JSON) }}"
          echo "json object toJSON(fromJSON)=${{ toJson(fromJson(env.JSON)) }}"
          echo "name=${{ toJson(fromJson(env.JSON).name) }}"
          echo "age=${{ toJson(fromJson(env.JSON).age) }}"
          echo "city=${{ toJson(fromJson(env.JSON).city) }}"
  populate-json:
    runs-on: ubuntu-latest
    outputs:
      person: ${{ steps.populate-json.outputs.person }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Populate JSON object
        shell: bash
        id: populate-json
        env:
          JSON: '{"name": "John", "age": 30, "city": "New York"}'
        run: |
            echo "PERSON=$JSON" >> $GITHUB_ENV
            echo "person=${{ toJson(env.JSON) }}" >> $GITHUB_OUTPUT
            echo "PERSON=$JSON"
      - name: Display JSON object
        shell: bash
        run: |
          echo "Person=${{ env.PERSON }}"
  json-processor:
    runs-on: ubuntu-latest
    needs: [populate-json]
    steps:
      - name: Print person
        run: |
          echo "Person=${{ needs.populate-json.outputs.person }}"