name: Push to feature branch
on:
  push:
    branches:
      - 'feature/*'
jobs:
  config:
    name: Prepare configuration
    runs-on: ubuntu-latest
    outputs:
      java_config: ${{ steps.config.outputs.java_config }}
      java_config_json: ${{ toJSON(steps.config.outputs.java_config) }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - id: config
        run: |          
          echo "title='GitHub Actions'" >> "$GITHUB_OUTPUT"
          echo "java_config=$(jq -c '.' '.github/java-config.json')" >> "$GITHUB_OUTPUT"
      - name: Print title
        run: echo ${{ steps.config.outputs.title }}
      - name: Print java config
        run: echo ${{ steps.config.outputs.java_config }}
      - name: Print maven config (maven config is not ready)
        run: echo ${{ steps.config.outputs.maven_config }}
  evaluate:
    name: Evaluate configuration
    runs-on: ubuntu-latest
    needs:
      - config
    steps:
      - name: Print java config
        run: echo ${{ needs.config.outputs.java_config }}
      - name: Print version
        run: echo ${{ fromJSON(needs.config.outputs.java_config_json).version }}